### ISSUE TITLE
Icons not appearing in yabai space labels in sketchybar, shows name from icon_map.sh

### ISSUE THREAD

**Issue by jktam** [crissNb472/dotfiles#3]
Hi, I'm struggling to understand how fonts/icons work in sketchybar (or yabai?). My issue in partiular is like in the screenshot.

<img width="1680" alt="image" src="https://github.com/crissNb/dotfiles/assets/2642695/55b53f2e-3253-454c-8a76-75d4982b26d3">

I've installed a variety of fonts such as hack nerd font, sf symbols, sf pro, etc. Whatever I can find out from the sketchybar github and your dots.

I can see that the code in sketchybar/plugins/yabai.sh (lines 50-56) calls sketchybar/plugins/icon_map.sh. Can you help me understand this, as it seems to print the names of the icons in the yabai space labels in the sketchybar?

Thanks!

**Comment by crissNb** [comment]
You're most likely missing the [sketchybar-app-font](https://github.com/kvndrsslr/sketchybar-app-font).
